- name: ansible filters practing
  hosts: local
  connection: local 
  vars:
    topics: linux, shellscript,ansible,terraform
    COURSE: "Devops with ansible , I am learning"
    myIp: "234.456.235.457"
    tagsmap:
      name: ansible
      project: roboshop
      component: catalogue
    tagsList:  [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

      
  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hii Prathyusha, {{ GREETING | default('good morning!') }}"

  - name: convert the string in to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert the dictionary or map  in to list
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}"

  - name: convert the list in to map
    ansible.builtin.debug:
      msg: "{{ tagsList| items2dict }}"


  - name: convert the string into upper case
    ansible.builtin.debug:
      msg: "{{ COURSE | upper }}"
  

  - name: convert the string into lower case
    ansible.builtin.debug:
      msg: "{{ COURSE | lower}}"

  - name: check ipv4
    ansible.builtin.debug:
      msg: "{{ myIp | ansible.utils.ipv4 }}