- name: check idempotency
  become: yes
  hosts: local
  connection: local
  tasks:
  - name: user creation
    ansible.builtin.user:
      user_name: pradush
    register: user_name


  - name: print user name
    ansible.builtin.debug:
      msg: "{{ user_name }}"
